#!/usr/local/bin/zsh
# This hook is run after every virtualenv is activated.

project_name=`basename "$VIRTUAL_ENV"`

# Save our prompt strings so we can reset them later.
#
# We also manipulate the prompt string so we remove the ($project_name) from it.
export _OLD_PS1="`echo $PS1 | sed s/\($project_name\)//`"
export _OLD_PROMPT="`echo $PROMPT | sed s/\($project_name\)//`"

# Set our new prompt strings.
# Change "matt" if your username is matt and don't like the prompt strings.
if [ "$USER" = "matt" ]; then
    export PS1=$'\n(%{$fg_bold[green]%}$project_name%{$reset_color%}) $(rb_prompt) in $(directory_name) $(git_dirty)$(need_push)\n› '
    export PROMPT=$'\n(%{$fg_bold[green]%}$project_name%{$reset_color%}) $(rb_prompt) in $(directory_name) $(git_dirty)$(need_push)\n› '
else
    export PS1="(%{${fg[green]}%}$project_name%{$reset_color%}) $_OLD_PS1"
    export PROMPT="(%{${fg[green]}%}$project_name%{$reset_color%}) $_OLD_PROMPT"
fi

# Set project private ENV vars.
export `get-env $project_name`

# Make sure we cd into the project directory if it exists.
if [ -d $PROJECT_HOME/$project_name ]; then
    cd $PROJECT_HOME/$project_name
fi
