#!/bin/sh
#
# bootstrap
#
# Install dependencies.

# Inspired bootstrap install scripts from:
#   davidxia's dotfiles (https://github.com/davidxia/bootstrap_dotfiles/)
#   joshdick's dotfiles (https://github.com/joshdick/dotfiles)

OUTPUT=/tmp/dotfiles-bootstrap
DOTFILES_ROOT="`pwd`"

set -e

echo ''
echo '' > $OUTPUT

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[00;34mUser Input Needed\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mok\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  echo "See $OUTPUT for more information."
  exit
}

configure_git () {
  if ! [ -f git/gitconfig.symlink ]
  then
    info 'gitconfig'
    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" git/gitconfig.symlink.example > git/gitconfig.symlink
    success 'gitconfig'
  fi

  info 'git submodule init'
  git submodule init >> $OUTPUT 2>&1
  success 'git submodule init'

  info 'git submodule update'
  git submodule init >> $OUTPUT 2>&1
  success 'git submodule update'
}

link_files () {
  ln -s $1 $2
  success "linked $1 to $2"
}

install_dotfiles () {
  info 'installing dotfiles'

  for file in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
  do
    dest="$HOME/.`basename \"${file%.*}\"`"

    if [ -f $dest ] || [ -d $dest ]
    then
      while true
      do
        user "`basename $file` exists - [s]kip, [o]verwrite, [b]ackup?"
        read -n 1 action

        case "$action" in
          o )
            rm -rf $dest
            success "removed $dest"

            link_files $file $dest

            break
            ;;
          b )
            mv $dest $dest\.backup
            success "moved $dest to $dest.backup"

            link_files $file $dest

            break
            ;;
          s )
            success "skipped $file"
            break
            ;;
          * )
            ;;
        esac
      done

    else
      link_files $file $dest
    fi

  done

  success 'dotfiles'
}

configure_git
install_dotfiles

# If we are on a mac, lets install and setup homebrew
[ "$(uname -s)" == "Darwin" ] && . homebrew/install.sh $OUTPUT

echo ''
echo '  All installed!'
